const messages = {
  Success: {
    SUCCESS: 'Success',
    SUCCESS_MESSAGE: 'Successfully',
    SUCCESS_MESSAGE_CREATE: 'Successfully created',
    SUCCESS_MESSAGE_UPDATE: 'Successfully updated',
    SUCCESS_MESSAGE_DELETE: 'Successfully deleted',
    SUCCESS_MESSAGE_LOGIN: 'Successfully logged in',
    SUCCESS_MESSAGE_LOGOUT: 'Successfully logged out',
    SUCCESS_MESSAGE_CREATE_USER: 'Successfully created user',
    SUCCESS_MESSAGE_UPDATE_USER: 'Successfully updated user',
    SUCCESS_MESSAGE_DELETE_USER: 'Successfully deleted user',
    SUCCESS_MESSAGE_CREATE_ROLE: 'Successfully created role',
    SUCCESS_MESSAGE_UPDATE_ROLE: 'Successfully updated role',
    SUCCESS_MESSAGE_DELETE_ROLE: 'Successfully deleted role',
    SUCCESS_MESSAGE_CREATE_PERMISSION: 'Successfully created permission',
  },
  Error: {
    ERROR: 'Error',
    ERROR_MESSAGE: 'Error',
    ERROR_MESSAGE_CREATE: 'Error creating',
    ERROR_MESSAGE_UPDATE: 'Error updating',
    ERROR_MESSAGE_DELETE: 'Error deleting',
    ERROR_MESSAGE_LOGIN: 'Error logging in',
    ERROR_MESSAGE_LOGOUT: 'Error logging out',
    ERROR_MESSAGE_CREATE_USER: 'Error creating user',
    ERROR_MESSAGE_UPDATE_USER: 'Error updating user',
    ERROR_MESSAGE_DELETE_USER: 'Error deleting user',
    ERROR_MESSAGE_CREATE_ROLE: 'Error creating role',
    ERROR_MESSAGE_UPDATE_ROLE: 'Error updating role',
    ERROR_MESSAGE_DELETE_ROLE: 'Error deleting role',
    ERROR_MESSAGE_CREATE_PERMISSION: 'Error creating permission',
  },
  Warning: {
    WARNING: 'Warning',
    WARNING_MESSAGE: 'Warning',
    WARNING_MESSAGE_CREATE: 'Warning creating',
    WARNING_MESSAGE_UPDATE: 'Warning updating',
    WARNING_MESSAGE_DELETE: 'Warning deleting',
    WARNING_MESSAGE_LOGIN: 'Warning logging in',
    WARNING_MESSAGE_LOGOUT: 'Warning logging out',
    WARNING_MESSAGE_CREATE_USER: 'Warning creating user',
    WARNING_MESSAGE_UPDATE_USER: 'Warning updating user',
    WARNING_MESSAGE_DELETE_USER: 'Warning deleting user',
    WARNING_MESSAGE_CREATE_ROLE: 'Warning creating role',
    WARNING_MESSAGE_UPDATE_ROLE: 'Warning updating role',
    WARNING_MESSAGE_DELETE_ROLE: 'Warning deleting role',
    WARNING_MESSAGE_CREATE_PERMISSION: 'Warning creating permission',
  },
  Info: {
    INFO: 'Info',
    INFO_MESSAGE: 'Info',
    INFO_MESSAGE_CREATE: 'Info creating',
    INFO_MESSAGE_UPDATE: 'Info updating',
    INFO_MESSAGE_DELETE: 'Info deleting',
    INFO_MESSAGE_LOGIN: 'Info logging in',
    INFO_MESSAGE_LOGOUT: 'Info logging out',
    INFO_MESSAGE_CREATE_USER: 'Info creating user',

    INFO_MESSAGE_UPDATE_USER: 'Info updating user',
    INFO_MESSAGE_DELETE_USER: 'Info deleting user',
    INFO_MESSAGE_CREATE_ROLE: 'Info creating role',
    INFO_MESSAGE_UPDATE_ROLE: 'Info updating role',
    INFO_MESSAGE_DELETE_ROLE: 'Info deleting role',
    INFO_MESSAGE_CREATE_PERMISSION: 'Info creating permission',
  },
};
export default messages;
